#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: silve45345
#    password: xobyrujlulhbcwrf
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true